DATA:
  IMG_SIZE: 352
MODEL:
  TYPE: pst
  NAME: swin_base_patch4_window12_352_finetune_patch_selection
  DROP_PATH_RATE: 0.5
  SWIN:
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 12
TRAIN:
  EPOCHS: 50
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
TEST:
  CROP: False
MODEL_DECODER:
  D_MODEL: 512
  NHEAD: 8
  NUM_DECODER_LAYERS: 6
  DIM_FEEDFORWARD: 2048
  DROPOUT: 0.1
  ACTIVATION: relu
  NORMALIZE_BEFORE: False
  RETURN_INTERMEDIATE_DEC: False
