DATA:
  IMG_SIZE: 224
MODEL:
  TYPE: pst
  NAME: swin_base_patch4_window12_352_finetune_patch_selection
  # TYPE: swin
  # NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.1
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6, 2 ]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7
TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
TEST:
  CROP: False
MODEL_DECODER:
  D_MODEL: 512
  NHEAD: 8
  NUM_DECODER_LAYERS: 6
  DIM_FEEDFORWARD: 2048
  DROPOUT: 0.1
  ACTIVATION: relu
  NORMALIZE_BEFORE: False
  RETURN_INTERMEDIATE_DEC: False
