DATA:
  IMG_SIZE: 352
  BATCH_SIZE: 16
MODEL:
  TYPE: pst
  NAME: swin_base_patch4_window12_352_finetune_patch_selection
  DROP_PATH_RATE: 0.1
  SWIN:
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 6 ]
    NUM_HEADS: [ 3, 6, 12 ]
    OUT_INDICES: [0, 1, 2]
    PATCH_SIZE: 44
    WINDOW_SIZE: 2
TRAIN:
  EPOCHS: 90
  WARMUP_EPOCHS: 5
  WEIGHT_DECAY: 1e-8
  BASE_LR: 2e-05
  WARMUP_LR: 2e-08
  MIN_LR: 2e-07
TEST:
  CROP: False
MODEL_DECODER:
  D_MODEL: 96
  NHEAD: 8
  NUM_DECODER_LAYERS: 6
  DIM_FEEDFORWARD: 2048
  DROPOUT: 0.1
  ACTIVATION: relu
  NORMALIZE_BEFORE: False
  RETURN_INTERMEDIATE_DEC: False
